# syntax=docker/dockerfile:1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Where are we working
ARG WORK_DIR="/workdir"
ARG NEMORL_DIR="${WORK_DIR}/nemo_rl"

ARG NEMORL_COMMIT="4806fc0ae43c2b44505f90455e705d3ad2454874"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG OCI_SOURCE="unknown"
ARG OCI_REVISION="unknown"
ARG OCI_CREATED="unknown"
ARG OCI_DESCRIPTION="unknown"
ARG CSCS_ALPS_GIT_COMMIT_SHORT="unknown"

LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      org.opencontainers.image.description="${OCI_DESCRIPTION}" \
      com.cscs.alps.git.repo="${OCI_SOURCE}" \
      com.cscs.alps.git.commit="${OCI_REVISION}" \
      com.cscs.alps.git.commit_short="${CSCS_ALPS_GIT_COMMIT_SHORT}"

# Install uv at /usr/local/bin in case the root home directory is bind mounted
# We need `uv` because the NeMoRL repo makes heavy use of it.
ARG UV_VERSION=0.11.18
RUN curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | XDG_BIN_HOME=/usr/local/bin sh

# This will ensure that the venv is build at a static location.
ENV UV_PROJECT_ENVIRONMENT="/opt/venv"

# Let's put the cache at a specific well known location.
ENV UV_CACHE_DIR="/opt/uv_cache"

# This environment variables are important for building.
ENV CPLUS_INCLUDE_PATH=/usr/local/cuda/include/cccl

# The base exports also 8.0 which leads to failure to build certain components.
ENV TORCH_CUDA_ARCH_LIST="9.0"

# Already exported in the base.
#ENV CUDA_PATH="/usr/local/cuda-13.1/"

# Needed for installation of `DeepGEMM`.
# NOTE: In the `nemo` container one must override `PYTHONPATH`, here it might not be needed.
ARG DEEP_GEMM_SCRIPTS="${WORK_DIR}/deep_gemm_patch"
ENV PYTHONPATH="${DEEP_GEMM_SCRIPTS}:"

# Now pulling NeMoRL
WORKDIR "${WORK_DIR}"

# Clone Nemo and check out the last known PATH.
RUN git clone https://github.com/NVIDIA-NeMo/RL.git "${NEMORL_DIR}"  	&& \
	cd "${NEMORL_DIR}" 						&& \
	git checkout --detach "${NEMORL_COMMIT}"			&& \
	git submodule update --init --recursive

# Now we need to download `DeepGEMM` to extract the patches for building it.
# NOTE: The commit that NeMoRL's `pyproject.toml` file references, `67fc64863d43521080bf2005e6528d0fceee9510`does not exist in the
#	_official_ repo, but in a fork. For some reason `uv` manages to find it, `git-ls-remote` also finds it. But we are using
#	a commit that also works.
RUN git clone --depth 1 https://github.com/deepseek-ai/DeepGEMM.git 	&& \
	mkdir -p "${DEEP_GEMM_SCRIPTS}"					&& \
	cp -r DeepGEMM/scripts "${DEEP_GEMM_SCRIPTS}"			&& \
	rm -rf DeepGEMM

# Now we move into the NeMoRL folder.
WORKDIR "${NEMORL_DIR}"

# Now install NeMoRL.
# - The venv of NeMoRL is located at `${UV_PROJECT_ENVIRONMENT}`
# - Some additional components are installed inside the `venvs` folder of the project.
RUN uv venv --seed --system-site-packages "${UV_PROJECT_ENVIRONMENT}"

# TODO: Find out why `--no-install-project` is given and why the original uses `hardlink`.
RUN uv sync --link-mode symlink --locked --no-install-project

# Now we perform the "install" of the helper, this will pull them into the cache such that they
#  are installed faster when they are needed.
# NOTE: In the original `vllm` used `hardlink` as mode, but I changed it to `symlink`.
RUN uv sync --link-mode symlink --locked --extra vllm --no-install-project
RUN uv sync --link-mode symlink --locked --extra mcore --no-install-project
RUN uv sync --link-mode symlink --locked --extra automodel --no-install-project
RUN uv sync --link-mode symlink --locked --extra modelopt --no-install-project
RUN uv sync --link-mode symlink --locked --all-groups --no-install-project

# The NeMo Dockerfile also removes some files related to ray, we do not do that.
# Furthermore, we will now install the project in full, i.e. without `--no-install-project`.
RUN uv sync --link-mode hardlink --locked
