# syntax=docker/dockerfile:1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG REMOVE_HPCX_DIRS=""

ARG XPMEM_REF=3bcab55479489fdd93847fa04c58ab16e9c0b3fd
ARG GDRCOPY_VER=2.5.1

ARG CASSINI_HEADERS_VERSION=release/shs-13.0.0
ARG CXI_DRIVER_VERSION=release/shs-13.0.0
ARG LIBCXI_VERSION=release/shs-13.0.0

ARG LIBFABRIC_COMMIT=f8262817c337d615a1acceea6cd4ecb526ce548b
ARG LIBFABRIC_PATCH="libfabric/fi_writemsg.f826281.patch"

ARG NCCL_VER=2.29.2-1
ARG NCCL_PATCH="nccl/net.cc.2.29.2-1.patch"

ARG UCX_VERSION=1.19.1
ARG UCC_VERSION=1.6.0
ARG OMPI_VER=5.0.9

ARG AWS_OFI_NCCL_COMMIT=eb9877e9cfecf725dba0794a5e0fc06f8fdf7f3f
ARG AWS_OFI_NCCL_PATCH="aws-ofi-nccl/endpoint_mr.eb9877e.patch"

ARG NVSHMEM_VER=3.4.5-0

ARG NCCL_TESTS_VER=2.17.8
ARG OSU_VERSION=7.5.2

ARG PIP_PACKAGES="flask-restful einops sentencepiece transformers tiktoken wandb nvidia-modelopt[hf]"

COPY Alps-Images/patches/ /opt/alps/patches/
COPY Alps-Images/common/install-alps-hpc-stack.sh /opt/alps/install-alps-hpc-stack.sh

RUN set -eux; \
    chmod +x /opt/alps/install-alps-hpc-stack.sh; \
    /opt/alps/install-alps-hpc-stack.sh

COPY Alps-Images/common/alps-runtime.env /opt/alps/env/alps-runtime.env

RUN set -eux; \
    chmod 0644 /opt/alps/env/alps-runtime.env; \
    printf '%s\n' 'if [ -f /opt/alps/env/alps-runtime.env ]; then . /opt/alps/env/alps-runtime.env; fi' \
        > /etc/profile.d/99-alps-env.sh

COPY Alps-Images/common/alps-runtime-warning.txt /opt/alps/env/alps-runtime-warning.txt
COPY Alps-Images/common/alps-runtime-warning.sh /opt/alps/env/alps-runtime-warning.sh
COPY Alps-Images/common/alps-runtime-warning.py /opt/alps/env/alps-runtime-warning.py
COPY Alps-Images/common/install-alps-runtime-warnings.sh /opt/alps/env/install-alps-runtime-warnings.sh

RUN set -eux; \
    chmod +x /opt/alps/env/install-alps-runtime-warnings.sh; \
    /opt/alps/env/install-alps-runtime-warnings.sh

ENV \
    NCCL_VERSION="${NCCL_VER}" \
    NVSHMEM_VERSION="${NVSHMEM_VER}"
