ARG BASE_IMAGE
FROM ${BASE_IMAGE}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG OCI_SOURCE="unknown"
ARG OCI_REVISION="unknown"
ARG OCI_CREATED="unknown"
ARG CSCS_ALPS_GIT_COMMIT_SHORT="unknown"

LABEL org.opencontainers.image.source="${OCI_SOURCE}" \
      org.opencontainers.image.revision="${OCI_REVISION}" \
      org.opencontainers.image.created="${OCI_CREATED}" \
      com.cscs.alps.git.repo="${OCI_SOURCE}" \
      com.cscs.alps.git.commit="${OCI_REVISION}" \
      com.cscs.alps.git.commit_short="${CSCS_ALPS_GIT_COMMIT_SHORT}"

#ARG MEGATRON_REPO="https://github.com/swiss-ai/Megatron-LM.git"
#ARG MEGATRON_COMMIT="08c9941f1f761b0758918744713176285a20b0e7" # merge-250908
ARG MEGATRON_REPO="https://github.com/boeschf/Megatron-LM.git"
ARG MEGATRON_COMMIT="669c4e8ffcc100cb3cfda3bf577b24dbb5541dd4"

RUN set -eux; \
    git clone "${MEGATRON_REPO}" /opt/megatron; \
    cd /opt/megatron; \
    git checkout -q "${MEGATRON_COMMIT}"; \
    test "$(git rev-parse HEAD)" = "${MEGATRON_COMMIT}"; \
    python3 setup.py build_ext --inplace;

# Tests shipped with the image
COPY Alps-Images/apps/apertus-1p5/tests/ /opt/tests/apertus-1p5/
RUN chmod -R a+rX /opt/tests/apertus-1p5

RUN set -eux; \
    python -m pip install --no-cache-dir --force-reinstall nvidia-ml-py==13.590.48

WORKDIR /opt/megatron
